a=int(input("Enter the first number:"))
b=int(input("Enter the second number:"))
print("The sum of the numbers is:",a+b)
print("The difference between the numbers is",a-b)
print("The product of the numbers is:",a*b)
print("The quotient of the numbers is:",a/b)
print("The answer for the integer division is:",a//b)
print("The cube of the first number is:", a**3)
